version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_URI=893605159071.dkr.ecr.us-east-2.amazonaws.com/pipeline
      - DOCKER_LOGIN_PASSWORD=$(aws ecr get-login-password  --region us-east-2)
      - docker login -u AWS -p $DOCKER_LOGIN_PASSWORD https://893605159071.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t  $REPOSITORY_URI:friends-${CODEBUILD_BUILD_NUMBER} .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:friends-${CODEBUILD_BUILD_NUMBER}
      - echo writing image definitions file...
      - printf '[{"name":"ashu","imageUri":"%s"}]' $REPOSITORY_URI:friends-${CODEBUILD_BUILD_NUMBER} > imagedefinitions.json
      - cat imagedefinitions.json 
      - pwd
artifacts:
    files: imagedefinitions.json
